---

- set_fact:
    stack_name: "iam-{{ item.name | regex_replace('[_.]', '-') }}-stack"

- name: is_stack_present
  shell: aws cloudformation describe-stacks --region "{{ region }}" --stack-name "{{ stack_name }}"
  args:
    executable: /bin/bash
  register: is_stack_present
  ignore_errors: yes

- name: "iam-{{ item.name }}-stack"
  cloudformation:
    stack_name: "{{ stack_name }}"
    region: "{{ region }}"
    state: "{{ stack_status }}"
    template: "roles/iam_users/files/iam-users-cf.json"
    template_parameters:
      UserName: "{{ item.name }}"
      FirstPassword: "{{ first_password }}"
      Groups: "{{ item.groups | map('quote') | join(',') }}"
  when: (stack_status == 'present') or (stack_status == 'absent' and is_stack_present|success)

- name: "collect-iam-{{ item.name }}-stack"
  cloudformation_facts:
    stack_name: "{{ stack_name }}"
    all_facts: true
    region: "{{ region }}"
  when: stack_status == "present"

- set_fact:
    "iam_{{ item.name | regex_replace('[-.]', '_') }}_facts": "{{ cloudformation }}"
  when: not ansible_check_mode and stack_status == "present"
