---

instances:
  - name: bastion-host-in-vpc-with-nat-public1-subnet
    subnet: public1
    type: "{{ instance_type | default('micro') }}"

  - name: bastion-host-in-vpc-with-nat-public2-subnet
    subnet: public2
    type: "{{ instance_type | default('micro') }}"
