---

- name: "iam-{{ service }}-user-roles-stack"
  cloudformation:
    stack_name: "iam-{{ service }}-user-roles-stack"
    region: "{{ region }}"
    state: "{{ stack_status }}"
    template: "roles/iam_roles_for_users/files/iam-roles-for-users-cf.json"
    template_parameters:
      ServiceName: "{{ service }}"

- name: "collect-iam-{{ service }}-user-roles-stack"
  cloudformation_facts:
    stack_name: "iam-{{ service }}-user-roles-stack"
    all_facts: true
    region: "{{ region }}"

- set_fact:
    "iam_{{ service | regex_replace('[-.]', '_') }}_user_roles_facts": "{{ cloudformation }}"
  when: not ansible_check_mode
