---

- set_fact:
    stack_name: "iam-{{ service | regex_replace('[_.]', '-') }}-user-roles-stack"

- name: is_stack_present
  shell: aws cloudformation describe-stacks --region "{{ region }}" --stack-name "{{ stack_name }}"
  args:
    executable: /bin/bash
  register: is_stack_present
  ignore_errors: yes

- name: "iam-{{ service }}-user-roles-stack"
  cloudformation:
    stack_name: "{{ stack_name }}"
    region: "{{ region }}"
    state: "{{ stack_status }}"
    template: "roles/iam_roles_for_users/files/iam-roles-for-users-cf.json"
    template_parameters:
      ServiceName: "{{ service }}"
  when: (stack_status == 'present') or (stack_status == 'absent' and is_stack_present|success)

- name: "collect-iam-{{ service }}-user-roles-stack"
  cloudformation_facts:
    stack_name: "{{ stack_name }}"
    all_facts: true
    region: "{{ region }}"
  when: stack_status == "present"

- set_fact:
    "iam_{{ service | regex_replace('[-.]', '_') }}_user_roles_facts": "{{ cloudformation }}"
  when: not ansible_check_mode and stack_status == "present"
