---

- hosts: all
  gather_facts: yes
  connection: local
  roles:
    - role: ec2_with_vpc_and_nat
      tags:
        - ec2

    - role: ec2_with_vpc_no_nat
      tags:
        - ec2

    - role: vpc_without_nat
      tags:
        - vpc

    - role: vpc_with_nat
      tags:
        - vpc

    - role: iam_managed_policies
      tags:
        - iam

    - role: iam_roles_for_compute
      tags:
        - iam

    - role: iam_users
      tags:
        - iam

    - role: iam_roles_for_users
      tags:
        - iam

    - role: iam_groups
      tags:
        - iam
