---

- hosts: all
  gather_facts: yes
  connection: local
  roles:
    - role: iam_managed_policies
      tags:
        - iam_managed_policies
        - iam

    - role: iam_roles_for_compute
      tags:
        - iam_roles_for_compute
        - iam

    - role: iam_users
      tags:
        - iam_users
        - iam

    - role: iam_roles_for_users
      tags:
        - iam_roles_for_groups
        - iam

    - role: iam_groups
      tags:
        - iam_groups
        - iam
