---

- hosts: all
  gather_facts: yes
  connection: local
  roles:
    - role: ec2_with_vpc_and_nat
      tags:
        - ec2

    - role: rds_with_vpc_and_nat
      tags:
        - rds

    - role: bastion_host_in_vpc_with_nat
      tags:
        - bastion

    - role: security_groups
      tags:
        - sg

    - role: vpc_with_nat
      tags:
        - vpc

    - role: iam_managed_policies
      tags:
        - iam

    - role: iam_roles_for_compute
      tags:
        - iam

    - role: iam_users
      tags:
        - iam

    - role: iam_roles_for_users
      tags:
        - iam

    - role: iam_groups
      tags:
        - iam
